project:
  type: website
  render:
    - "*.qmd"
  
website:
  title: "Reclamation"
  navbar:
    left:
      - notebooks/abandoned_wells.qmd
      - notebooks/leaf_process.qmd
      - notebooks/eda_hfi.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
