project:
  type: website
  render:
    - "!notebooks/eda_hfi.qmd"
    - "*.qmd"
  
website:
  title: "Reclamation"
  navbar:
    left:
      - notebooks/abandoned_wells.qmd
      - notebooks/leaf_process.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
